name: Audit # Nombre del fichero .yml
on: push
jobs:
  audit:
    runs-on: ubuntu-latest
    name: Audit
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Check if .editorconfig exists
        uses: andstor/file-existence-action@v1
        with:
<<<<<<< HEAD
          files: ".editorconfig"
=======
          files: '.editorconfig'
>>>>>>> 6007f77890f6486e64cc2cb8322536fd64eaf80e
          allow_failure: true
      - name: EditorConfig validation
        uses: snow-actions/eclint@v1.0.1
      - name: Ensure node_modules is ignored by Git
        uses: dkershner6/gitignore-parser@v1
        with:
<<<<<<< HEAD
          must_deny: "node_modules/"
=======
          must_deny: 'node_modules/'
>>>>>>> 6007f77890f6486e64cc2cb8322536fd64eaf80e
      - name: Install modules
        run: npm ci
      - name: ESLint validation
        run: npx eslint --ignore-path .gitignore .
      - name: Check commit message length
        uses: gsactions/commit-message-checker@v1
        with:
<<<<<<< HEAD
          pattern: "^[^#].{10,74}"
          error: "The commit message length must be between 10 and 72"
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          excludeTitle: "true" # optional: this excludes the title of a pull request
          checkAllCommitMessages: "true" # optional: this checks all commits associated with a pull request
=======
          pattern: '^[^#].{10,74}'
          error: 'The commit message length must be between 10 and 72'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
>>>>>>> 6007f77890f6486e64cc2cb8322536fd64eaf80e
